### ISSUE TITLE
Neo4J connection error

### ISSUE THREAD

**Issue by ralf-berger** [ude-soco/elas-official#105]
Both `sc-elas-official-backend-5-studycompass-web` and `sc-elas-official-backend-5-studycompass-worker` fail with:

```
Failed to connect to Neo4j database: 'NoneType' object has no attribute 'replace'
```

**Comment by shoebjoarder** [comment]
I believe the issue is due to the declaration of the environment variable. The `backend/5-studycompass` defined the Neo4j environment as `NEO4J_HOST` but in the compose.yml file it is defined as `NEO4J_HOSTNAME`.

**Comment by shoebjoarder** [comment]
Yes, you are absolutely right, and the issue appears because the `NEO4J_HOST` environment variable is considered by the 5-studycompass service as not declared or as empty, which means that the `os.environ.get("NEO4J_HOST")` returns `None` and therefore `NEOMODEL_NEO4J_BOLT_URL` appears to be `None` as well. I am not quite sure why the service is not reading the  `NEO4J_HOST` environment variable correctly, but I am assuming one of the following two reasons, either

1. One or more of the environment variables (`NEO4J_USERNAME`, `NEO4J_PASSWORD`, `NEO4J_HOSTNAME`, or `NEO4J_PORT`) used to construct `NEO4J_HOST` are not set or are empty. This could result in an incomplete Bolt URL which might not be recognized by the Neomodel library, leading to a None value for `NEO4J_HOST` as mentioned previously, OR
2. Both the servers are not receiving the environment variables correctly at all.

Could you please try adding some print statements to confirm if the environment variables are correctly set in the application?

```
print("NEO4J_USERNAME:", os.environ.get("NEO4J_USERNAME"))
print("NEO4J_PASSWORD:", os.environ.get("NEO4J_PASSWORD"))
print("NEO4J_HOSTNAME:", os.environ.get("NEO4J_HOSTNAME"))
print("NEO4J_PORT:", os.environ.get("NEO4J_PORT"))
print("NEO4J_HOST:", os.environ.get("NEO4J_HOST"))
```
