### ISSUE TITLE
Inter-service connectivity between Eureka clients on K8s

### ISSUE THREAD

**Issue by ralf-berger** [ude-soco/elas-official#85]
backend-2-api-gateway in K8s env complains:
```
[…] 500 Server Error for HTTP GET "/api/e3selector/e3-courses/"
io.netty.channel.ConnectTimeoutException: connection timed out: ⏎
  sc-elas-official-backend-1-service-registry.elas-official-edge.svc.cluster.local/10.43.193.175:8004
```

**Comment by shoebjoarder** [comment]
I have observed that there are some changes already made to the file, and I have the following suggestion below, based on the [documentation](https://pypi.org/project/py-eureka-client/#:~:text=Registering%20to%20Eureka%20Server):
```python
try:
    EUREKA_HOST_NAME = os.environ.get("HOST")
    EUREKA_PORT = os.environ.get("EUREKA_PORT")
    INSTANCE_HOST = os.environ.get("INSTANCE_HOST")
    eureka_client.init(
        eureka_server=f"http://{EUREKA_HOST_NAME}:{EUREKA_PORT}/eureka",  # type: ignore
        app_name="ELAS-AUTH",
        instance_port=int(os.environ.get("DJANGO_PORT", "8002")),
        instance_host=INSTANCE_HOST,  # type: ignore
    )
```
The `instance_ip=socket.gethostbyname(EUREKA_HOST_NAME)` is not necessarily required, which can be removed. However, the `instance_host` property should be provided. If we are using the "host" networking driver, we can set the `instance_host` to the hostname of the host machine. However, if we are using the "bridge" driver (or a custom network), we should set the `instance_host` to the IP address of the container within the Docker network.

We have to keep in mind that we need to retrieve the IP address of the container and pass it to the application every time the container is started, and I guess in order to automate this process, we could modify the Dockerfile or our container orchestration configuration to automatically retrieve the container's IP address and set the `INSTANCE_HOST` environment variable.
